-- MySQL Script generated by MySQL Workbench
-- Fri Mar 13 21:34:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pictures` (
  `pic_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  PRIMARY KEY (`pic_id`),
  UNIQUE INDEX `pic_id_UNIQUE` (`pic_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`object_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`object_types` (
  `ot_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `name` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(200) NULL,
  `pic_id` INT NULL,
  PRIMARY KEY (`ot_id`),
  UNIQUE INDEX `ot_id_UNIQUE` (`ot_id` ASC),
  INDEX `fk_object_types_object_types1_idx` (`parent_id` ASC),
  INDEX `fk_object_types_pictures1_idx` (`pic_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_object_types_object_types1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`object_types` (`ot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_object_types_pictures1`
    FOREIGN KEY (`pic_id`)
    REFERENCES `mydb`.`pictures` (`pic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objects` (
  `object_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `ot_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`object_id`),
  INDEX `fk_objects_object_types_idx` (`ot_id` ASC),
  UNIQUE INDEX `object_id_UNIQUE` (`object_id` ASC),
  INDEX `fk_objects_objects1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_objects_object_types`
    FOREIGN KEY (`ot_id`)
    REFERENCES `mydb`.`object_types` (`ot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objects_objects1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`objects` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attr_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attr_types` (
  `attr_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`attr_type_id`),
  UNIQUE INDEX `attr_type_id_UNIQUE` (`attr_type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attr_type_defs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attr_type_defs` (
  `attr_type_def_id` INT NOT NULL AUTO_INCREMENT,
  `attr_type_id` INT NOT NULL,
  `ot_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`attr_type_def_id`),
  UNIQUE INDEX `attr_type_def_id_UNIQUE` (`attr_type_def_id` ASC),
  INDEX `fk_attr_type_defs_attr_types1_idx` (`attr_type_id` ASC),
  INDEX `fk_attr_type_defs_object_types1_idx` (`ot_id` ASC),
  CONSTRAINT `fk_attr_type_defs_attr_types1`
    FOREIGN KEY (`attr_type_id`)
    REFERENCES `mydb`.`attr_types` (`attr_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attr_type_defs_object_types1`
    FOREIGN KEY (`ot_id`)
    REFERENCES `mydb`.`object_types` (`ot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attr_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attr_groups` (
  `attr_group_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `name` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`attr_group_id`),
  UNIQUE INDEX `attr_group_id_UNIQUE` (`attr_group_id` ASC),
  INDEX `fk_attr_groups_attr_groups1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_attr_groups_attr_groups1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`attr_groups` (`attr_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attributes` (
  `attr_id` INT NOT NULL AUTO_INCREMENT,
  `attr_type_id` INT NOT NULL,
  `attr_type_def_id` INT NOT NULL,
  `attr_group_id` INT NULL,
  `name` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`attr_id`),
  UNIQUE INDEX `attr_id_UNIQUE` (`attr_id` ASC),
  INDEX `fk_attributes_attr_types1_idx` (`attr_type_id` ASC),
  INDEX `fk_attributes_attr_type_defs1_idx` (`attr_type_def_id` ASC),
  INDEX `fk_attributes_attr_groups1_idx` (`attr_group_id` ASC),
  CONSTRAINT `fk_attributes_attr_types1`
    FOREIGN KEY (`attr_type_id`)
    REFERENCES `mydb`.`attr_types` (`attr_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attributes_attr_type_defs1`
    FOREIGN KEY (`attr_type_def_id`)
    REFERENCES `mydb`.`attr_type_defs` (`attr_type_def_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attributes_attr_groups1`
    FOREIGN KEY (`attr_group_id`)
    REFERENCES `mydb`.`attr_groups` (`attr_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`references` (
  `attr_id` INT NOT NULL,
  `reference` INT NOT NULL,
  `object_id` INT NOT NULL,
  INDEX `fk_references_attributes1_idx` (`attr_id` ASC),
  INDEX `fk_references_objects1_idx` (`reference` ASC),
  INDEX `fk_references_objects2_idx` (`object_id` ASC),
  CONSTRAINT `fk_references_attributes1`
    FOREIGN KEY (`attr_id`)
    REFERENCES `mydb`.`attributes` (`attr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_references_objects1`
    FOREIGN KEY (`reference`)
    REFERENCES `mydb`.`objects` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_references_objects2`
    FOREIGN KEY (`object_id`)
    REFERENCES `mydb`.`objects` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`list_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`list_values` (
  `list_value_id` INT NOT NULL AUTO_INCREMENT,
  `attr_type_def_id` INT NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`list_value_id`),
  UNIQUE INDEX `list_value_id_UNIQUE` (`list_value_id` ASC),
  INDEX `fk_list_values_attr_type_defs1_idx` (`attr_type_def_id` ASC),
  CONSTRAINT `fk_list_values_attr_type_defs1`
    FOREIGN KEY (`attr_type_def_id`)
    REFERENCES `mydb`.`attr_type_defs` (`attr_type_def_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`params`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`params` (
  `attr_id` INT NOT NULL,
  `ot_id` INT NOT NULL,
  `value` VARCHAR(500) NULL,
  `list_value_id` INT NULL,
  `date` DATE NULL,
  INDEX `fk_params_attributes1_idx` (`attr_id` ASC),
  INDEX `fk_params_object_types1_idx` (`ot_id` ASC),
  INDEX `fk_params_list_values1_idx` (`list_value_id` ASC),
  CONSTRAINT `fk_params_attributes1`
    FOREIGN KEY (`attr_id`)
    REFERENCES `mydb`.`attributes` (`attr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_params_object_types1`
    FOREIGN KEY (`ot_id`)
    REFERENCES `mydb`.`object_types` (`ot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_params_list_values1`
    FOREIGN KEY (`list_value_id`)
    REFERENCES `mydb`.`list_values` (`list_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attr_object_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attr_object_types` (
  `attr_id` INT NOT NULL,
  `ot_id` INT NOT NULL,
  `required` TINYINT NOT NULL,
  INDEX `fk_attr_object_types_attributes1_idx` (`attr_id` ASC),
  INDEX `fk_attr_object_types_object_types1_idx` (`ot_id` ASC),
  CONSTRAINT `fk_attr_object_types_attributes1`
    FOREIGN KEY (`attr_id`)
    REFERENCES `mydb`.`attributes` (`attr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attr_object_types_object_types1`
    FOREIGN KEY (`ot_id`)
    REFERENCES `mydb`.`object_types` (`ot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configs` (
  `name` VARCHAR(200) NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;